[versions]
spotless = "8.2.1"
ktlint = "1.5.0"
kotlin = "2.3.10"
intellij-platform = "2.11.0"

[libraries]

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform" }